name: Cypress Tests + Telegram Alert

on: [push, pull_request]

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: |
          npx cypress run || echo "FAILED" > status.txt

      - name: Telegram Notification
        if: always()
        run: |
          RESULT=$(cat status.txt 2>/dev/null || echo "PASSED")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
            -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
            -d text="✅ Cypress tests $RESULT 🚀\nRepo: ${{ github.repository }}\nCommit: ${{ github.sha }}"
